<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<!--<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>-->
<div class="header-content-left col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <?php if ($block->isHomePage()):?>
        <!-- <strong class="logo">     -->
        <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <?php else: ?>
        <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <?php endif ?>
            <strong>Smile</strong>
            <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
                class="img-responsive"
                title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
    <?php if ($block->isHomePage()):?>
        <!-- </strong> -->
        </a>
    <?php else:?>
        </a>
    <?php endif?>
</div>
