                    <li class="last">
                        <div class="box-email"><span class="pull-left"><em class="fa fa-envelope-o">&nbsp;</em></span>
                            <div class="media-body pull-left">
                                <p>
                                <a href="mailto:<?php echo !empty($block->getEmail()[0]['option_value']) ?$block->getEmail()[0]['option_value']:'';?>">
                                    <?php echo !empty($block->getEmail()[0]['option_value']) ?$block->getEmail()[0]['option_value']:'';?>
                               </p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>