<div class="header-block1 col-lg-5 col-md-5 col-sm-5 col-xs-12 pull-left hidden-sm hidden-xs ">
    <div class="box-support">
        <ul>
            <li class="first">
                <div class="box-phone"><span class="pull-left"><em class="fa fa-phone">&nbsp;</em></span>
                <div class="media-body pull-left">
                <p><span>Hotline:</span>
                <?php if(!empty($block->getPhone()[0]['option_value'])) { ?>
                    <?php echo $block->getPhone()[0]['option_value'];?>
                <?php } ?>
                </p>
                </div>
                </div>
            </li>