<?php print_r($block->getOptions());?>

<div class="accordion">
    <div class="entry-edit form-inline">
        <div class="section-config active">
        <div class="entry-edit-head admin__collapsible-block"><span id="web_default_layouts-link" class="entry-edit-head-link"></span>
        <a id="web_default_layouts-head" href="#web_default_layouts-link" onclick="Fieldset.toggleCollapse('web_default_layouts', 'http://local.magento.com/admin/admin/system_config/state/key/88221783da10fc3f5f57437aabd898eed1f4fcfe60d1b8743f76aee3f98d8fad/'); return false;" class="">Header Settings</a></div>
        <input id="web_default_layouts-state" name="config_state[web_default_layouts]" type="hidden" value="0">
        <fieldset class="config admin__collapsible-block" id="web_default_layouts" style="display: none;">  <legend>Header settings</legend>
            <table cellspacing="0" class="form-list">
                <colgroup class="label"></colgroup>
                <colgroup class="value"></colgroup>
                <colgroup class="scope-label"></colgroup>
                <colgroup class=""></colgroup>
                <tbody>
                    <tr id="row_web_default_layouts_default_cms_layout">
                        <td class="label">
                            <label for="header_phone"><span>Header Phone</span></label>
                        </td>
                        <td class="value">
                            <input type="text" name="header_phone" value="asasasa" class="input-text admin__control-text" id="header_phone">
                        </td>
                        <td class=""></td>
                    </tr>
                    <tr id="row_web_default_layouts_default_cms_layout">
                        <td class="label">
                            <label for="header_email"><span>Header Email</span></label>
                        </td>
                        <td class="value">
                            <input type="text" name="header_email" value="asasasa" class="input-text admin__control-text" id="header_email">
                        </td>
                        <td class=""></td>
                    </tr>
                </tbody>
            </table>
        </fieldset>      
    </div>
    </div>        
</div>
