<button data-bind=" click: getProduct">Get Next Product</button>
<table>
   <thead>
   <tr>
       <th>ID</th>
       <th>Product Name</th>
       <th>Product Price</th>
       <th>Preview</th>
   </tr>
   </thead>
   <tbody data-bind="foreach: productList">
   <tr>
       <td data-bind="text: entity_id"></td>
       <td data-bind="text: name"></td>
       <td data-bind="text: price"></td>
       <td><img data-bind="attr: {src: src}" width="120" height="150" alt="Product Image"></td>
   </tr>
   </tbody>
</table>